---
galaxy_info:
  author: Pratik Argade
  description: Install and configure Apache web server
  company: 
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - all
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - all
    - name: EL
      versions:
        - "8"
        - "9"
        - all
  galaxy_tags:
    - apache
    - httpd
    - web-server
    - webserver

dependencies: []

