---
galaxy_info:
  author: Pratik Argade
  description: Configure Two-Factor Authentication (2FA) using Google Authenticator for SSH access
  company: 
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - all
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - all
    - name: EL
      versions:
        - "8"
        - "9"
        - all
  galaxy_tags:
    - 2fa
    - two-factor
    - authentication
    - google-authenticator
    - otp
    - security
    - ssh
    - pam

dependencies: []

